### ISSUE TITLE
LinkedIn Accept Invitations:  Cannot read property 'href' of null

### ISSUE THREAD

**Issue by homeforce** [phantombuster/api-store#196]
----- BUG -----
* Container 39385420 started in azu-us-west-or-botrunner-0 (Wed Dec 12 2018 11:16:05 GMT+0000 (UTC))
* Got dependency LinkedIn Accept Invitations.js
* Got dependency lib-LinkedIn.js
* Got dependency lib-StoreUtilities.js
* Spawning Node v8.10.0
🔄 Connecting to LinkedIn...
✅ Connected successfully as **{user}**
🔄 Scrolling down...
❌ Error: evaluate: code evaluation failed: exception thrown from page: Uncaught (in promise) TypeError: Cannot read property 'href' of null
* Process finished with an error (exit code: 1) (Wed Dec 12 2018 11:16:19 GMT+0000 (UTC))

**Comment by homeforce** [comment]
----- New Launch -----
* Container 39476507 started in azu-us-west-ca-botrunner-10 (Thu Dec 13 2018 12:08:00 GMT+0000 (UTC))
* Got dependency LinkedIn Accept Invitations.js
* Got dependency lib-LinkedIn.js
* Got dependency lib-StoreUtilities.js
* Spawning Node v8.10.0
🔄 Connecting to LinkedIn...
✅ Connected successfully as Tyas Lambrechts
🔄 Scrolling down...
ℹ️ No LinkedIn thread URL found for https://www.linkedin.com/in/nas-b-525050128/, accepting invitation whitout sending a message
✅ A total of 1 profile has been added
	https://www.linkedin.com/in/nas-b-525050128/
✅ Job done!
* Process finished successfully (exit code: 0) (Thu Dec 13 2018 12:08:16 GMT+0000 (UTC))

Does not send a message to the person? #

**Comment by TASnomad** [comment]
Hello @homeforce, 

The API only send messages when a connection request has a note with it.
That's why you have this message on your API logs.

**Comment by homeforce** [comment]
Hii @TASnomad 

I have a message in the API 
![image](https://user-images.githubusercontent.com/10156034/49941299-5f50e080-fee2-11e8-87cb-e92590ac27e5.png)


greetings

**Comment by TASnomad** [comment]
Right, your API configuration isn't the problem with this issue.

This message shows up if the API wasn't able to find a link to start a LinkedIn conversation (it happens when there is no note left with a request connection).

This situation happens only when you configure a message and don't check the "Only accept invitations with a message" option.

The API was made to send messages to every request connections but only to those who have a note with it.

Sorry if my explanations were confusing

**Comment by homeforce** [comment]
ooh i see.... thanks for helping and fixing the API.
