### ISSUE TITLE
LinkedIn Profile Scraper: TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by paps** [phantombuster/api-store#35]
See logs of agent 8326 of user 1458

→ Notify PB user 1458

**Comment by TASnomad** [comment]
Commit 0c2ed8e provides a fix, here the changements:

- Slowing down a bit the API in order to loaded all sections of the profile
- The TypeError seems to be a bad return for skills from the browser context function
if there weren't any skills, the function will return an empty array

PB user 1458 is notified
